### ISSUE TITLE
Set the working directory of a wrapper to SF_REPORT_ROOT

### ISSUE THREAD

**Issue by hansspanjers** [boxingbeetle/softfab#24]
Currently the working directory of a wrapper is the directory in which the Task Runner was started. This is very inconvenient, e.g. most of the reports are written in SF_REPORT_ROOT. Now, you have to precede all log file names by SF_REPORT_ROOT or you should 'cd' to it.

Also, a mistake by the developer could lead to 'hard to find files' since he is not aware that his files are placed in the not expected 'Task Runner' directory.

It would be better to set the working directory of a wrapper to SF_REPORT_ROOT.

**Comment by mthuurne** [comment]
I looked in the Java docs and both [ProcessBuilder](https://docs.oracle.com/javase/8/docs/api/java/lang/ProcessBuilder.html#directory-java.io.File-) (the preferred way to start processes) and [Runtime.exec()](https://docs.oracle.com/javase/8/docs/api/java/lang/Runtime.html#exec-java.lang.String:A-java.lang.String:A-java.io.File-) (which we use now) support overriding the working directory, so this shouldn't be too hard.
